server:
  port: 8082

mnsx:
  rpc:
    port: 6679

spring:
  datasource:
    url: jdbc:mysql://vm.mnsx.top:3306/rpc_demo?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver